
services:

  # Viewer
  paste:
    image: ghcr.io/serlithnetwork/flare-viewer

  # Backend
  jet:
    image: ghcr.io/serlithnetwork/jet
    ports:
      - "9420:9420"
      - "9430:9430"
    volumes:
      - pictures:/opt/jet/pictures
      - config:/opt/jet/config

volumes:
  data: {}